<script setup lang="ts">
useHead({ link: [{ rel: "canonical", href: "https://crescenzosorrentino.com/cookie-policy" }] })

useSeoMeta({
  title: "Cookie Policy",
  description: "Cookie policy for crescenzosorrentino.com: how we use cookies and how to manage your preferences.",
  ogTitle: "Cookie Policy — Crescenzo Sorrentino",
  ogDescription: "Cookie policy for crescenzosorrentino.com: how we use cookies and how to manage your preferences.",
  ogUrl: "https://crescenzosorrentino.com/cookie-policy",
  twitterTitle: "Cookie Policy — Crescenzo Sorrentino",
  twitterDescription: "Cookie policy for crescenzosorrentino.com: how we use cookies and how to manage your preferences.",
})

// v-html è l'equivalente di dangerouslySetInnerHTML di React.
// Sicuro in questo caso perché il contenuto è statico e scritto da noi.
const content = `
<h1 class="cp-h1">Cookie Policy</h1>
<div class="cp-dates">
  <p>Effective date: April 14, 2026</p>
  <p>Last updated: April 14, 2026</p>
</div>

<h2>What are cookies?</h2>
<div class="cp-p">
  <p>This Cookie Policy explains what cookies are, how we use them, the types of cookies we use (i.e., the information we collect using cookies and how that information is used), and how to manage your cookie settings.</p>
  <p>Cookies are small text files used to store small pieces of information. They are stored on your device when a website loads in your browser. These cookies help ensure that the website functions properly, enhance security, provide a better user experience, and analyse performance to identify what works and where improvements are needed.</p>
</div>

<h2>How do we use cookies?</h2>
<div class="cp-p">
  <p>Like most online services, our website uses both first-party and third-party cookies for various purposes. First-party cookies are primarily necessary for the website to function properly and do not collect any personally identifiable data.</p>
  <p>The third-party cookies used on our website primarily help us understand how the website performs, track how you interact with it, keep our services secure, deliver relevant advertisements, and enhance your overall user experience while improving the speed of your future interactions with our website.</p>
</div>

<h2>Types of cookies we use</h2>
<div class="cky-audit-table-element"></div>

<h2>Manage cookie preferences</h2>
<a class="cky-banner-element">Consent Preferences</a>
<div class="cp-p">
  <p>You can modify your cookie settings anytime by clicking the 'Consent Preferences' button above. This will allow you to revisit the cookie consent banner and update your preferences or withdraw your consent immediately.</p>
  <p>Additionally, different browsers offer various methods to block and delete cookies used by websites. You can adjust your browser settings to block or delete cookies. Below are links to support documents on how to manage and delete cookies in major web browsers.</p>
  <p>Chrome: <a target="_blank" rel="noopener noreferrer" href="https://support.google.com/accounts/answer/32050">https://support.google.com/accounts/answer/32050</a></p>
  <p>Safari: <a target="_blank" rel="noopener noreferrer" href="https://support.apple.com/en-in/guide/safari/sfri11471/mac">https://support.apple.com/en-in/guide/safari/sfri11471/mac</a></p>
  <p>Firefox: <a target="_blank" rel="noopener noreferrer" href="https://support.mozilla.org/en-US/kb/clear-cookies-and-site-data-firefox?redirectslug=delete-cookies-remove-info-websites-stored&redirectlocale=en-US">https://support.mozilla.org/en-US/kb/clear-cookies-and-site-data-firefox?redirectslug=delete-cookies-remove-info-websites-stored&redirectlocale=en-US</a></p>
  <p>Internet Explorer: <a target="_blank" rel="noopener noreferrer" href="https://support.microsoft.com/en-us/topic/how-to-delete-cookie-files-in-internet-explorer-bca9446f-d873-78de-77ba-d42645fa52fc">https://support.microsoft.com/en-us/topic/how-to-delete-cookie-files-in-internet-explorer-bca9446f-d873-78de-77ba-d42645fa52fc</a></p>
  <p>If you are using a different web browser, please refer to its official support documentation.</p>
</div>

<p class="cp-p">Cookie Policy generated by <a target="_blank" rel="noopener noreferrer" href="https://www.cookieyes.com/?utm_source=CP&utm_medium=footer&utm_campaign=UW">CookieYes - Cookie Policy Generator</a></p>
`
</script>

<template>
  <main>
    <section class="section">
      <div class="container container--narrow">
        <!-- v-html renderizza HTML grezzo — usare solo con contenuto fidato -->
        <div class="content" v-html="content" />
      </div>
    </section>
  </main>
</template>

<style scoped>
/* :deep() è l'equivalente di :global() dei CSS Modules di React:
   raggiunge gli elementi generati da v-html ignorando lo scoping. */

.content :deep(.cp-h1) {
  font-family: var(--font-headings);
  font-size: var(--text-3xl);
  font-weight: 300;
  color: var(--color-primary);
  margin-bottom: var(--space-4);
  line-height: 1.3;
}

.content :deep(.cp-dates) {
  font-size: var(--text-sm);
  color: var(--text-secondary);
  margin-bottom: var(--space-8);
}

.content :deep(h2) {
  font-size: var(--text-lg);
  font-weight: 600;
  color: var(--color-primary);
  margin-block: var(--space-6) var(--space-3);
}

.content :deep(.cp-p p),
.content :deep(.cp-p) {
  font-size: var(--text-sm);
  color: var(--text-primary);
  line-height: 1.7;
  margin-bottom: var(--space-4);
}

.content :deep(a) {
  color: var(--color-accent);
  text-decoration: underline;
}

.content :deep(.cky-banner-element) {
  display: inline-block;
  padding: var(--space-2) var(--space-6);
  font-size: var(--text-sm);
  border: 1px solid var(--border);
  border-radius: 4px;
  cursor: pointer;
  margin-bottom: var(--space-6);
  color: var(--text-primary);
}
</style>
